# Generated by Django 5.1.6 on 2026-03-03 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Amount donated (verified from blockchain)')),
                ('tx_hash', models.CharField(help_text='Ethereum transaction hash (MetaMask / Ganache)', max_length=66, unique=True)),
                ('integrity_hash', models.CharField(help_text='Derived checksum for DB integrity verification', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, help_text='Registered donor (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='app.trust_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Utilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.FloatField()),
                ('purpose', models.CharField(max_length=500)),
                ('category', models.CharField(default='Other', max_length=50)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='utilization_proofs/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizations', to='app.donation')),
                ('trust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trust_profile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_utilizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
